### ISSUE TITLE
Failed to parse query: must use ["allof", expr...]

### ISSUE THREAD

**Issue by brentvatne** [facebook/watchman#118] opened 2015-07-13 23:58 UTC
```
Error: failed to parse query: must use ["allof", expr...]
   at BunserBuf.<anonymous> (/Users/michael/project/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
   at emitOne (events.js:77:13)
   at BunserBuf.emit (events.js:169:7)
   at BunserBuf.process (/Users/michael/project/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:289:10)
   at /Users/michael/dev/project/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:244:12
   at doNTCallback0 (node.js:408:9)
   at process._tickCallback (node.js:337:13)
```

As you can see above, this is with react-native - tried various versions including HEAD with no luck, same error. Using iojs 2.3.4 via nvm. Any ideas?

**Comment by wez** [comment] 2015-07-14 00:58
Sounds like either a React-Native issue or a sane issue; watchman is reporting that the query expression doesn't parse.  Unfortunately the error message isn't showing us enough context to diagnose it here.
@amasad do you have enough info to suggest whether we should track this in react-native or sane?

**Comment by wez** [comment] 2015-07-24 18:32
I'm going to close this issue because it sounds more like a react-native issue and we have no additional data to work with.

**Closed by wez** 2015-07-24 18:32 UTC

**Comment by brentvatne** [comment] 2015-07-24 19:03
@wez - makes sense, we ended up resolving through a series of uninstall / reinstalling every related dependency, sorry no solid steps for fixing it.

**Comment by mvayngrib** [comment] 2015-08-03 22:42
@brentvatne ran into this working with a react-native project, any progress in identifying the cause? Any tips for resolving it in my project?

**Comment by amasad** [comment] 2015-09-08 08:26
Is this still happening? We can potentially catch this and add the query in the error message. Please point me out to the react-native issue if there is one so we can discuss there.

**Comment by frantic** [comment] 2016-01-14 02:52
@amasad I just got this error too recently when using more than 1 root. Related RN issues: https://github.com/facebook/react-native/issues/3405 and https://github.com/facebook/react-native/issues/3973. Adding more logging certainly won't hurt.

**Comment by frantic** [comment] 2016-01-14 03:08
This is the command it is sending:
```
[
  "query",
  "/private/tmp/frantic-a14U4P",
  {
    "suffix": ["js", "json", "png", "jpg", "jpeg", "bmp", "gif", "webp"],
    "expression": [
      "allof",
      ["type", "f"],
      "exists",
      ["anyof"]
    ],
    "fields": ["name"]
  }
]
```

when running

```
node node_modules/react-native/local-cli/cli.js start --root /tmp/frantic-a14U4P
```

**Comment by amasad** [comment] 2016-01-14 06:00
I can't see anything wrong with this query. @wez any ideas?

Is this is now consistently reproing?

**Comment by frantic** [comment] 2016-01-14 06:06
Yep, react-native v0.17.0:

```
$ react-native init SomeApp
$ cd SomeApp
$ mkdir /tmp/frantic-a14U4P
$ node node_modules/react-native/local-cli/cli.js start --root /tmp/frantic-a14U4P

["query","/private/tmp/frantic-a14U4P",{"suffix":["js","json","png","jpg","jpeg","bmp","gif","webp"],"expression":["allof",["type","f"],"exists",["anyof"]],"fields":["name"]}]
Error building DependencyGraph:
 Error: failed to parse query: must use ["allof", expr...]
    at BunserBuf.<anonymous> (/Users/frantic/code/react-native-run/ReactSandbox/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/frantic/code/react-native-run/ReactSandbox/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/frantic/code/react-native-run/ReactSandbox/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by wez** [comment] 2016-01-14 15:10
That `["anyof"]` at the bottom is the problem; both `anyof` and `allof` require 1 or more expression terms, but there are none.
You should remove it from the expression that is being built and passed in if it is in this "empty" state

**Comment by frantic** [comment] 2016-01-14 18:51
Thanks @wez! @amasad lets continue the discussion here https://github.com/facebook/react-native/issues/3973

**Comment by wez** [comment] 2016-01-14 19:07
FWIW, we can change watchman to support 0+ terms in the future, but since the React Native using OSS community tends to have a wider range of watchman versions deployed than we do inside FB, it's wise to fix up the query generation in react native in the meantime
