### ISSUE TITLE
Uninstall subtlety & how I fixed a Watchman hang

### ISSUE THREAD

**Issue by onpaws** [facebook/watchman#361] opened 2016-09-15 05:58 UTC
First off wanted to say thanks to everyone involved in this excellent app!

This issue involves both the Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/44b5c7447c6aab5af310b6eac0f76d56e180cc7c/Formula/watchman.rb) and `watchman`.

Today something in my `watchman` state dir caused a hang[1] just like https://github.com/facebook/watchman/issues/358#issue-176593548.
I also solved by https://github.com/facebook/watchman/issues/358#issuecomment-246672605.

Confusingly (to me), `brew uninstall watchman` didn't touch that directory.
On the one hand, it would have saved me a few hours today. On the other hand, @wez based on your https://github.com/facebook/watchman/issues/358#issuecomment-246779161 it sounds like that folder is potentially valuable for debugging.

Inside I see a log file (helpful) but also pid/state/socket, the inclusion of which in `brew uninstall`  could have saved me this trouble.

@jerzerak, @wez, (any other maintainers): thoughts? how do other packages handle this? 
Is there a `brew uninstall -complete $PACKAGE` or something?
My naive thought: feels like a good compromise may be retaining/leaving the logfile but removing the rest.

---
[1] Launching the RN Packager, `watchman watch-del-all` or `react-native start --reset-cache` all just hung (kind of like running `cat` by itself).

React Native 0.33, OS X 10.11.6, Homebrew `0992951`, node 6.5.0

**Comment by onpaws** [comment] 2016-09-15 06:13
Bonus naive thought: What are the implications in simply keeping the state in `/tmp/`?

I ask because during my troubleshooting I had tried rebooting and as you can imagine it didn't make a difference.

**Comment by wez** [comment] 2016-09-15 17:04
This is a duplicate of #358, so I'm closing this in favor of that.  I'll add some comments to answer some of your questions over there so that we don't fragment into too many threads.

**Closed by wez** 2016-09-15 17:04 UTC
