### ISSUE TITLE
node fb-watchman 1.3 leads to Error: shutdown ENOTCONN

### ISSUE THREAD

**Issue by spruce** [facebook/watchman#134] opened 2015-08-16 12:46 UTC
Using ember-cli / sane / fb-watchman leads to an error on iojs 2.0.1
switching out fb-watchman 1.3.0 with 1.2.0 fixes the issue
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: shutdown ENOTCONN
    at exports._errnoException (util.js:843:11)
    at Socket.onSocketFinish (net.js:208:26)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:163:7)
    at finishMaybe (_stream_writable.js:473:14)
    at endWritable (_stream_writable.js:482:3)
    at Socket.Writable.end (_stream_writable.js:448:5)
    at Socket.end (net.js:385:31)
    at ChildProcess.<anonymous> (/Users/spruce/Sites/test/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/index.js:164:17)
```

**Comment by grabbou** [comment] 2015-08-16 13:16
Same with React Native.

**Comment by wez** [comment] 2015-08-16 16:50
Sorry about this.  What's the easiest way to reproduce this issue?

**Comment by wez** [comment] 2015-08-16 17:03
Pushed a speculative fix in fb-watchman 1.4.0.
Would be great to have some steps to reproduce this so that I can confirm.

**Comment by grabbou** [comment] 2015-08-16 17:17
It's quite tricky to reproduce to be fair as I am using 3rd party package that uses it internally. But as it was occurring all the time, I think I can just re-run to see what happens.

**Comment by jsierles** [comment] 2015-08-16 20:02
This fix works for me with React Native 0.9.0.

**Comment by wez** [comment] 2015-08-17 17:41
I've had a couple of reports that this is good, so closing it out.

**Closed by wez** 2015-08-17 17:41 UTC

**Comment by stefanpenner** [comment] 2015-08-17 17:44
@wez can confirm, all appears well.
