### ISSUE TITLE
Error while loading shared libraries: double-conversion.dll:

### ISSUE THREAD

**Issue by andrzejpalemba** [facebook/watchman#681] opened 2019-02-15 16:09 UTC
I am getting errors while running watchman on Windows 7:

`watchman --version`
`C:/Program Files/watchman/watchman.exe: error while loading shared libraries: double-conversion.dll: cannot open shared object file: No such file or directory`

**Comment by wez** [comment] 2019-02-27 21:48
Duplicate of https://github.com/facebook/watchman/issues/675

**Closed by wez** 2019-02-27 21:48 UTC
Labels: windows

**Comment by wez** [comment] 2019-02-27 21:51
Actually, https://github.com/facebook/watchman/issues/683 has a better resolution
