### ISSUE TITLE
`watchman version` and `watchman shutdown server` hang in the terminal indefinitely

### ISSUE THREAD

**Issue by ostigley** [facebook/watchman#381] opened 2016-11-01 05:39 UTC
I'm finding that watchman is hanging in the background (called by react-native), or when run directly in the console. 

`watchman version` and `watchman shutdown-server` just hang in the terminal, indefinitely.   There is no response.  The CPU is not spinning. 

<img width="249" alt="screen shot 2016-11-01 at 6 36 43 pm" src="https://cloud.githubusercontent.com/assets/10747958/19880451/2cbe1ccc-a062-11e6-950b-1b25c3d11c1d.png">

watchman version: 
<img width="211" alt="screen shot 2016-11-01 at 6 38 36 pm" src="https://cloud.githubusercontent.com/assets/10747958/19880477/6cdaa1c2-a062-11e6-8f42-7033d83ebb9a.png">

OS: Sierra 10.12.1
Xcode: 8.1
node: v7.0.0

I've tried uninstalling and reinstalling watchman to no avail.  
brew upgrade has no effect, nor does brew doctor

**Comment by wez** [comment] 2016-11-01 19:32
Probably a duplicate of https://github.com/facebook/watchman/issues/358

**Comment by ostigley** [comment] 2016-11-01 19:46
Thanks for that @wez.   The following cleared up the issue for now
```
launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist
watchman version
```

**Closed** 2016-11-01 19:47 UTC
