### ISSUE TITLE
Request: Option to make BSER strings always UTF-8

### ISSUE THREAD

**Issue by bhamiltoncx** [facebook/watchman#123] opened 2015-08-03 22:27 UTC
By default, the JSON encoding mode of watchman throws an exception if any paths or other strings are not UTF-8 (thanks to jansson).

If you request BSER encoding, by design, watchman instead transfers the non UTF-8 byte arrays to the other side and expects the client to deal with the values.

It'd be really nice if clients could opt-in to "BSER with UTF-8 validation" mode so conversion from JSON to BSER were more simple. This can be done in a few ways:

1) Just throw an exception whenever any non-UTF-8 values are encoded to BSER (just like JSON mode)
2) Attempt to convert from `LC_CTYPE` to UTF-8 using `iconv()` or similar

**Comment by wez** [comment] 2015-08-03 23:39
Actually, the majority of our strings bypass the jansson UTF-8 checks for perf reasons(!)
We return the raw bytes regardless of whether you've asked for JSON or BSER.

If we did want to tackle UTF-8 cleanliness, we'd target this during crawling so that our internal data structures were guaranteed to be in UTF-8.  The issue is that the underlying filesystem APIs don't provide a portable or reliable way to determine the encoding of the file names; they are stored as binary strings and passed back to us as-is.

The CLI arguments are a slightly different problem; those are the main thing (perhaps the only thing?) that is locale sensitive in watchman.

**Comment by bgertzfield** [comment] 2015-08-04 02:58
> bypass the jansson UTF-8 checks for perf reasons(!)

Wow. What happens when we try to pass non-UTF-8 pathnames to jansson? (Or are those the strings that don't bypass the check?)

And yes, I totally understand the underlying issue, and I know there's no foolproof way to solve it on most *nix systems. An option to say "we only care about UTF-8 and throwing an error for anything else" would get us 99% of the way there.

**Comment by wez** [comment] 2015-08-04 03:49
We bypass the utf-8 checks for strings we create from file names we've observed during crawling or notifications.  The user input goes through the usual jansson checks.

**Comment by sid0** [comment] 2015-08-04 16:36
We can't really be UTF-8 clean internally -- Mercurial depends on Watchman returning byte strings via BSER.

**Comment by wez** [comment] 2016-05-23 23:16
Closing this in favor of @sid0's https://github.com/facebook/watchman/wiki/Better-Unicode-handling-plan

**Closed by wez** 2016-05-23 23:16 UTC
