### ISSUE TITLE
Windows Build missing

### ISSUE THREAD

**Issue by matale** [facebook/watchman#935] opened 2021-08-01 05:03 UTC
Installation instructions at https://facebook.github.io/watchman/docs/install.html point to here https://github.com/facebook/watchman/releases/latest but there is no windows zip.

**Comment by manuc66** [comment] 2021-08-04 09:38
See also https://github.com/facebook/watchman/issues/910

**Comment by n0mer** [comment] 2021-12-31 11:15
still missing, @kassens any timeline to restore build ?

**Comment by chadaustin** [comment] 2022-01-27 19:55
Duplicate of #910, will comment there

**Closed by chadaustin** 2022-01-27 19:55 UTC
