### ISSUE TITLE
Watchman consuming an entire CPU core during heavy file IO

### ISSUE THREAD

**Issue by benpeart** [facebook/watchman#535] opened 2017-09-20 20:23 UTC
When there is a lot of file IO in a watched directory, Watchman has high CPU usage which consumes an entire core.  I noticed this when running the git test suite but I suspect anything that generates a lot of file creates/deletes/modifications would show it as well.

$ watchman version
{
    "version": "4.9.0",
    "buildinfo": "928791f7c578dbcbb7760b73223ac58c9af50d19 2017-08-21T20:49:51.0000000Z"
}

$ watchman watch-list
{
    "version": "4.9.0",
    "roots": [
        "C:/git-sdk-64/usr/src/git"
    ]
}

There are no errors so no log entries.

**Comment by nicerr** [comment] 2017-10-04 21:38
I had the same problem. The solution suggested [here](https://github.com/facebook/nuclide/issues/528) worked for me:

https://github.com/facebook/nuclide/issues/528

**Comment by wez** [comment] 2017-12-20 18:36
I wonder if this was another manifestation of #548?

**Comment by wez** [comment] 2018-01-09 07:03
Based on this comment https://github.com/facebook/watchman/issues/508#issuecomment-356034466 I'm going to assume that this was the same root cause as #548 and close this issue out.

**Closed by wez** 2018-01-09 07:03 UTC
