### ISSUE TITLE
Binary fails to run because of missing libpcre.so.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by naddeoa** [facebook/watchman#522] opened 2017-08-18 18:05 UTC
Sorry if this is a duplicate, I couldn't find pcre mentioned in another issue. I tested this on v4.9.0 and v4.7.0.

Checking out the repo from source and building will result in a binary that fails because it is dynamically linked against libpcre.so.1. If I could install it then it would work just fine but it doesn't appear to be available in any of the stock repos (determined by running `apt-file find libpcre.so.1`). However, there are more recent versions available; libpcre.so.3 for example.

I was able to get it working by configuring it to explicitly use the later version.

```
sudo apt-get install libpcre3-dev
git clone https://github.com/facebook/watchman.git
cd watchman
./autogen.sh
./configure --with-pcre=/usr/bin/pcre-config
make
```

Shouldn't configure be able to determine that pcre isn't available on the system and/or find a valid version that is installed? Assuming my box isn't just weird, source builds should fail to run on 16.04 in general otherwise.

**Comment by wez** [comment] 2017-08-18 18:24
do you also have the `libpcre3` package installed?

Can you share the output from `ldd watchman` and the `config.log`?

**Comment by naddeoa** [comment] 2017-08-18 18:31
This is `ldd` after having given my `--with-pcre` switch to configure.

```
 ldd watchman
	linux-vdso.so.1 =>  (0x00007ffd497fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f06c9ca2000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f06c9a32000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f06c9667000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f8fc28f000)
```

Without that switch, it was `libpcre.so.1 => not found`.  I do also have the libpcre3 package installed, yes. I'll attach the log as a zip.

[watchman-log.zip](https://github.com/facebook/watchman/files/1235304/watchman-log.zip)

**Comment by naddeoa** [comment] 2017-08-18 18:42
This is `ldd` after having given my `--with-pcre` switch to configure.

```
 ldd watchman
	linux-vdso.so.1 =>  (0x00007ffd497fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f06c9ca2000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f06c9a32000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f06c9667000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f8fc28f000)
```

Without that switch, it was `libpcre.so.1 => not found`.  I do also have the libpcre3 package installed, yes. Anything in specific you want from the logs? Looks like there is a bunch of stuff in there about my system that I may not want to upload permanently.

**Comment by wez** [comment] 2017-08-18 19:47
Can you share the actual error that you're seeing?  That ldd output shows that watchman is successfully linked.

**Comment by naddeoa** [comment] 2017-08-18 20:10
I had to go rebuild watchman to get you the exact error, sorry.

```
./watchman: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

And the exact ldd output

```
	linux-vdso.so.1 =>  (0x00007ffef565c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4d9e537000)
	libpcre.so.1 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4d9e16c000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f847df2000)
```

**Comment by wez** [comment] 2017-08-19 16:14
What did you differently with this build from the last one that looked ok?
Please do share the `config.log` file too; it is key to understanding what `configure` found on your system.

**Comment by naddeoa** [comment] 2017-08-19 17:17
I explained the difference in the opening comment. Specifically, `./configure --with-pcre=/usr/bin/pcre-config`. It looks like it is only failing on my work computer. I couldn't reproduce it on my personal laptop. I can share the log but I'll have to sanitize it first. It has a bunch of stuff in it that I shouldn't just put online (internal names, file paths, etc).

**Comment by wez** [comment] 2017-08-30 22:39
I thought I'd already replied to this, wonder what happened to the text I wrote?
Anyway, I think that the issue is that you have multiple pcre versions installed, so configure requires you specify explicitly which one should be used.  I don't think that we strictly need to expend energy on making this more robust, but I won't turn away a well tested PR that improves things here, should someone really want this to get better :)

I'm going to close this out as I don't think there is anything more that we strictly need to do here.

**Closed by wez** 2017-08-30 22:39 UTC
