### ISSUE TITLE
Error installing watchman from source on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by istvanfedak** [facebook/watchman#879] opened 2020-12-18 02:27 UTC
Hi,

I tried to install watchman from source following the [installing from source](https://facebook.github.io/watchman/docs/install.html#installing-from-source) user guide. When I ran `make` I got an error.

Should I try to install the non stable release to see if the issue is fixed?

**Environment**: Ubuntu 20.04 LTS

**Steps to recreate**:
`$ sudo apt install libssl-dev autoconf automake libtool`

```
$ git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1
$ cd watchman 
$ ./autogen.sh
$ ./configure
$ make
```

**Output**:

```
$ make
make  all-am
make[1]: Entering directory '/home/User/Applications/watchman'
  CXX      scm/watchman-Mercurial.o
scm/Mercurial.cpp: In constructor ‘watchman::Mercurial::infoCache::infoCache(std::string)’:
scm/Mercurial.cpp:16:40: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct watchman::FileInformation’; use assignment or value-initialization instead [-Werror=class-memaccess]
   16 |   memset(&dirstate, 0, sizeof(dirstate));
      |                                        ^
In file included from scm/Mercurial.h:10,
                 from scm/Mercurial.cpp:3:
./FileInformation.h:18:8: note: ‘struct watchman::FileInformation’ declared here
   18 | struct FileInformation {
      |        ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:4446: scm/watchman-Mercurial.o] Error 1
make[1]: Leaving directory '/home/User/Applications/watchman'
make: *** [Makefile:1264: all] Error 2
```

**Comment by istvanfedak** [comment] 2020-12-18 02:33
I was able to install watchman using `sudo apt install watchman`

**Comment by chadaustin** [comment] 2022-01-27 20:01
The root cause of the build failures is fixed now.

**Closed by chadaustin** 2022-01-27 20:01 UTC
