### ISSUE TITLE
Build fails with 3.8.0

### ISSUE THREAD

**Issue by jzakrzewski** [facebook/watchman#156] opened 2015-10-01 20:25 UTC
Configure:
```
$ ./configure --prefix=$HOME/local
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for ranlib... ranlib
checking dependency style of gcc... gcc3
checking for arc... no
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib64/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python2.7/site-packages
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for library containing pthread_create... -lpthread
checking for library containing socket... none required
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking for mkostemp... yes
checking for kqueue... no
checking for port_create... no
checking for inotify_init... yes
checking for strtoll... yes
checking for localeconv... yes
checking for statfs... yes
checking for accept4... yes
checking for sys/vfs.h... yes
checking for sys/param.h... yes
checking for sys/mount.h... yes
checking for sys/statfs.h... yes
checking for sys/statvfs.h... yes
checking valgrind/valgrind.h usability... yes
checking valgrind/valgrind.h presence... yes
checking for valgrind/valgrind.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking CoreServices/CoreServices.h usability... no
checking CoreServices/CoreServices.h presence... no
checking for CoreServices/CoreServices.h... no
checking for backtrace... yes
checking for backtrace_symbols... yes
checking for struct statvfs.f_fstypename... no
checking for struct statvfs.f_basetype... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating thirdparty/jansson/jansson_config.h
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

Your build configuration:

        CPPFLAGS =  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
        CFLAGS = -g -O2  -Wall -Wextra -Wdeclaration-after-statement -g -gdwarf-2 -fno-omit-frame-pointer
        LDFLAGS = 
        prefix: /home/XXX/local
        version: 3.8.0
        state directory: /home/XXX/local/var/run/watchman
```
Followed by build and install:
```
$ make install
  CC       thirdparty/jansson/libwmanjson_a-dump.o
  CC       thirdparty/jansson/libwmanjson_a-error.o
  CC       thirdparty/jansson/libwmanjson_a-hashtable.o
  CC       thirdparty/jansson/libwmanjson_a-load.o
  CC       thirdparty/jansson/libwmanjson_a-memory.o
  CC       thirdparty/jansson/libwmanjson_a-pack_unpack.o
  CC       thirdparty/jansson/libwmanjson_a-strbuffer.o
  CC       thirdparty/jansson/libwmanjson_a-strconv.o
  CC       thirdparty/jansson/libwmanjson_a-value.o
  AR       libwmanjson.a
  CC       thirdparty/libtap_a-tap.o
  AR       libtap.a
  CC       watchman-argv.o
  CC       watchman-envp.o
  CC       watchman-spawn.o
  CC       watchman-opt.o
  CC       watchman-cfg.o
  CC       watchman-fstype.o
  CC       watchman-log.o
  CC       watchman-json.o
  CC       watchman-bser.o
  CC       watchman-hash.o
  CC       watchman-ht.o
  CC       watchman-ioprio.o
  CC       watchman-stream.o
  CC       watchman-stream_stdout.o
  CC       watchman-stream_unix.o
  CC       cmds/watchman-find.o
  CC       cmds/watchman-info.o
  CC       cmds/watchman-log.o
  CC       cmds/watchman-query.o
  CC       cmds/watchman-since.o
  CC       cmds/watchman-reg.o
  CC       cmds/watchman-subscribe.o
  CC       cmds/watchman-trigger.o
  CC       cmds/watchman-watch.o
  CC       cmds/watchman-debug.o
  CC       query/watchman-base.o
  CC       query/watchman-dirname.o
  CC       query/watchman-parse.o
  CC       query/watchman-eval.o
  CC       query/watchman-intcompare.o
  CC       query/watchman-type.o
  CC       query/watchman-suffix.o
  CC       query/watchman-match.o
  CC       query/watchman-pcre.o
  CC       query/watchman-name.o
  CC       query/watchman-fieldlist.o
  CC       query/watchman-since.o
  CC       query/watchman-empty.o
  CC       watcher/watchman-fsevents.o
  CC       watcher/watchman-helper.o
  CC       watcher/watchman-inotify.o
  CC       watcher/watchman-kqueue.o
  CC       watcher/watchman-portfs.o
  CC       watchman-listener.o
  CC       watchman-clientmode.o
  CC       watchman-main.o
  CC       watchman-root.o
  CC       watchman-state.o
  CC       watchman-string.o
  CCLD     watchman
  CC       tests/tests_argv_t-argv.o
  CC       tests_argv_t-argv.o
  CCLD     tests/argv.t
  CC       tests/tests_log_t-log.o
  CC       tests_log_t-log.o
  CCLD     tests/log.t
  CC       tests/tests_bser_t-bser.o
  CC       tests_bser_t-bser.o
  CCLD     tests/bser.t
  CC       tests/tests_wildmatch_t-wildmatch_test.o
  CCLD     tests/wildmatch.t
cd python && /usr/bin/python ./setup.py clean build_py -c -d . build_ext -i
running clean
running build_py
running build_ext
copying build/lib.linux-x86_64-2.7/pywatchman/bser.so -> pywatchman
make[1]: Entering directory '/home/XXX/src/watchman'
 /bin/mkdir -p '//home/XXX/local/bin'
  /usr/bin/install -c watchman '//home/XXX/local/bin'
cd python && /usr/bin/python ./setup.py install --prefix /home/XXX/local --root /
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
running egg_info
writing pywatchman.egg-info/PKG-INFO
writing top-level names to pywatchman.egg-info/top_level.txt
writing dependency_links to pywatchman.egg-info/dependency_links.txt
reading manifest file 'pywatchman.egg-info/SOURCES.txt'
writing manifest file 'pywatchman.egg-info/SOURCES.txt'
removing '/home/XXX/local/lib64/python2.7/site-packages/pywatchman-1.2.0-py2.7.egg-info' (and everything under it)
Copying pywatchman.egg-info to /home/XXX/local/lib64/python2.7/site-packages/pywatchman-1.2.0-py2.7.egg-info
running install_scripts
/usr/bin/install -c -d -m 777 /
/usr/bin/install: cannot change permissions of ‘/’: Operation not permitted
Makefile:2656: recipe for target 'install-exec-local' failed
make[1]: *** [install-exec-local] Error 1
make[1]: Leaving directory '/home/XXX/src/watchman'
Makefile:2470: recipe for target 'install-am' failed
make: *** [install-am] Error 2
```
Seems to be related to fe6f560964da409a3ba0d16c38f91717b73b89b5 but I know next to nothing about autotools.

**Comment by sid0** [comment] 2015-10-01 21:09
`/usr/bin/install: cannot change permissions of ‘/’: Operation not permitted`

Are you root? Are you on OS X El Capitan by any chance?

**Comment by jzakrzewski** [comment] 2015-10-02 07:57
I'm on gentoo. And no, I'm not root and I'm not going to be. I'm doing a local install to my home directory as the first line indicates: ```$ ./configure --prefix=$HOME/local```. And frankly I'm glad I'm not root as I wouldn't like if this line: ```/usr/bin/install -c -d -m 777 /``` was really executed...

**Comment by wez** [comment] 2015-10-02 15:19
the definition for that rule in Makefile.am is:

```
install-exec-local: py-install
if WATCHMAN_STATE_DIR
  ${INSTALL} -d -m 777 ${DESTDIR}${WATCHMAN_STATE_DIR}
  chmod g+s ${DESTDIR}${WATCHMAN_STATE_DIR}
  touch ${DESTDIR}${WATCHMAN_STATE_DIR}/.not-empty
endif
```

Can you check what the value of `WATCHMAN_STATE_DIR` is in the `Makefile` that got generated for you?

It would also be helpful to know what version of autoconf, automake you have, in case that is relevant.

**Comment by wez** [comment] 2015-10-03 23:31
I can't reproduce this.  I suspect something related to your specific version of autoconf or automake

**Comment by jzakrzewski** [comment] 2015-10-04 22:59
I'm on pretty recent versions of everything:
```
*  sys-devel/autoconf
      Latest version available: 2.69-r1
      Latest version installed: 2.69-r1
*  sys-devel/automake
      Latest version available: 1.15
      Latest version installed: 1.15
```
In the mean while I've nuked watchman's directory an re-cloned. Magically it has built and installed. I may only guess that somehow I had inconsistent state there. I hate autotools polluting the source tree...

**Comment by wez** [comment] 2015-10-05 15:20
Let's chalk this up to being in a weird state.  We can try to run this down if we get a way to reproduce it, but closing this out for now.

**Closed by wez** 2015-10-05 15:20 UTC

**Comment by JamieEi** [comment] 2017-09-28 17:44
Same problem and solution when upgrading from 4.7.0 to 4.9.0 on Ubuntu 16.04.
