### ISSUE TITLE
how to resolve 'failed to parse query: must use ["allof", expr...] when watchman installed

### ISSUE THREAD

**Issue by wumingli** [facebook/watchman#188] opened 2015-11-21 16:25 UTC
Looking for JS files in
   /Users/wumingli/www/reactTest 

[12:20:47 AM] <START> Building Dependency Graph
[12:20:47 AM] <START> Crawling File System
[12:20:47 AM] <START> Loading bundles layout
[12:20:47 AM] <END>   Loading bundles layout (0ms)

React packager ready.

Error building DepdendencyGraph:
 Error: failed to parse query: must use ["allof", expr...]
    at BunserBuf.<anonymous> (/Users/wumingli/www/reactTest/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/wumingli/www/reactTest/node_modules/bser/index.js:289:10)
    at /Users/wumingli/www/reactTest/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
Process terminated. Press <enter> to close the window

**Comment by wez** [comment] 2015-11-21 19:31
That error means that something sent a query to watchman that had a term like: `["allof"]`, but the `allof` term expects a list of 1 or more expressions.  It's a bug in whatever is producing that query.

**Comment by wez** [comment] 2015-11-25 04:41
Closing this out because it is not a watchman issue

**Closed by wez** 2015-11-25 04:41 UTC

**Comment by wumingli** [comment] 2015-11-25 06:25
thanks @wez ,but it's running okay without installing watchman.

**Comment by wez** [comment] 2015-11-25 06:30
Please file your issue against the react native project; the problem is in how it is using watchman, not with watchman itself
