### ISSUE TITLE
`watchman version` hangs (macOS, installed via brew)

### ISSUE THREAD

**Issue by amurchick** [facebook/watchman#371] opened 2016-09-26 07:08 UTC
OS: macOS 10.12 (16A323)
```
$ watchman -v
4.7.0

$ brew -v
Homebrew 1.0.4-7-g6e57355
Homebrew/homebrew-core (git revision e741; last commit 2016-09-26)
```

When run `watchman version` - watchman hangs
<img width="277" alt="screen shot 2016-09-26 at 14 06 26" src="https://cloud.githubusercontent.com/assets/1515699/18825430/920aed58-83f2-11e6-8f32-c0f53f6c7d07.png">

**Comment by fenichelar** [comment] 2016-09-26 15:44
Same.

OS: El Capitan (10.11.6)
Watchman: 4.7.0
Brew: 1.0.4

**Comment by wez** [comment] 2016-09-26 16:13
Try this: https://github.com/facebook/watchman/issues/358#issuecomment-247105934

**Comment by amurchick** [comment] 2016-09-27 14:05
```
amur@amur-mac:~$ launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist
amur@amur-mac:~$ watchman version
```
Still hangs

**Comment by fenichelar** [comment] 2016-09-27 14:23
I then uninstalled and reinstalled watchman using homebrew.

**Comment by wez** [comment] 2016-09-27 20:48
Weird.  Can you try adding the `-F` flag:

```
launchctl unload -F ~/Library/LaunchAgents/com.github.facebook.watchman.plist
```

If it is still hanging after that, I'd like you to collect some diagnostics:

* What does Console.app mention about watchman?
* What watchman process(es) are running?
* Please use Activity Monitor to "sample" any running watchman processes and attach the samples here

**Comment by amurchick** [comment] 2016-09-28 15:02
With `-F` flag still hangs

In `Console` when run `watchman version` add only this event:

![screen shot 2016-09-28 at 21 53 48](https://cloud.githubusercontent.com/assets/1515699/18918790/18bb9242-85c6-11e6-98e7-7922f00d5e5f.png)

`ps ax | grep watchman`:
```
~$ ps ax | grep watchman
 2978 s016  S+     0:00.02 /usr/local/Cellar/watchman/4.7.0/libexec/bin/watchman version
 3067 s017  S+     0:00.00 grep watchman
~$ 
```

`Samples`: [watchman-samples.txt](https://github.com/facebook/watchman/files/498591/watchman-samples.txt)

**Comment by stefanpenner** [comment] 2016-10-02 16:05
> Weird. Can you try adding the -F flag:
> 
> launchctl unload -F ~/Library/LaunchAgents/com.github.facebook.watchman.plist

seems to address the hang for me.

**Comment by amurchick** [comment] 2016-10-07 06:21
> seems to address the hang for me, which started after the first restart of my system in a long time
This does not helps for me.

**Comment by ryankask** [comment] 2016-10-10 19:03
This happened to me when I upgraded watchman from 4.6.0 to 4.7.0 using Homebrew and ran `brew clean`.

I restarted the system after upgrading to Safari 10 but the path in the plist was still `/usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman`, which doesn't exist, instead of `/usr/local/Cellar/watchman/4.7.0/libexec/bin/watchman`.

Doing the `launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist` (outside of tmux) and then `watchman version` fixed the issue.

**Comment by wez** [comment] 2016-10-12 18:26
This is a duplicate of #358

**Closed by wez** 2016-10-12 18:26 UTC

**Comment by amurchick** [comment] 2016-11-14 09:59
Helps to me:
1. Run `launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist` outside of `tmux`
2. Run `watchman version` outside of `tmux`

Thank you, @ryankask!

**Comment by nickzuber** [comment] 2017-10-24 00:11
For letting `watchman version` work within `tmux`, you can use a plugin like [tmux-MacOSX-pasteboard](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard).

Simply install with brew

```
$ brew install reattach-to-user-namespace
```

and then add something like this to your `.tmux.conf`

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

then just restart your tmux sessions

```
$ tmux kill-server
```
