### ISSUE TITLE
Windows install?

### ISSUE THREAD

**Issue by kentcdodds** [facebook/watchman#860] opened 2020-10-07 16:17 UTC
According to [windows install instructions in the documentation](https://facebook.github.io/watchman/docs/install.html#windows):

> - Download and extract the windows release from the latest release
> - It will be named something like watchman-vYYYY.MM.DD.00-windows.zip
> - It contains a bin folder. Move that somewhere appropriate and update your PATH environment to reference that location.

However, the latest release does not have a windows zip. The last release to ship with a windows zip is [v2020.08.17.00](https://github.com/facebook/watchman/releases/tag/v2020.08.17.00).

Is there a new installation recommendation?

**Comment by pruthvip** [comment] 2021-04-27 12:27
Is there any update on this??

**Comment by meladRaouf** [comment] 2021-09-27 03:40
Please check this issue https://github.com/facebook/watchman/issues/935

**Comment by chadaustin** [comment] 2022-02-10 22:12
Indeed, duplicate of #935, which is fixed by a9e3998839dc8b3761caf6078434d992e64592ad and 59bcfbf91d2a24ab580b8a78e384f133cc202383

**Closed by chadaustin** 2022-02-10 22:12 UTC
