### ISSUE TITLE
is latest wathcman.exe only avail from watchman-v2021.01.11.00-windows version

### ISSUE THREAD

**Issue by gaweki** [facebook/watchman#992] opened 2022-01-18 10:29 UTC
the link https://github.com/facebook/watchman/releases/tag/v2021.01.11.00

i had checked several release versions but for windows it doesn't apparent

**Comment by chadaustin** [comment] 2022-01-27 19:55
Duplicate of #910, will comment there

**Closed by chadaustin** 2022-01-27 19:55 UTC
Labels: windows
